//SideBar
export const SET_USER_PLAYLISTS = "SET_USER_PLAYLISTS";

//Homepage
export const SET_USER_BROWSE_RELEASES = "SET_USER_BROWSE_RELEASES";
export const SET_USER_BROWSE_FEATURED = "SET_USER_BROWSE_FEATURED";
export const SET_USER_BROWSE_CATEGORIES = "SET_USER_BROWSE_CATEGORIES";
export const SET_USER_BROWSE_LAST_PLAYED = "SET_USER_BROWSE_LAST_PLAYED";

//Cache Data
export const SAVE_DATA_PLAYLISTS = "SAVE_DATA_PLAYLISTS";
export const SAVE_DATA_ALBUMS = "SAVE_DATA_ALBUMS";
export const SAVE_DATA_CATEGORIES = "SAVE_DATA_CATEGORIES";

//Artists Page
export const SET_ARTIST_DETAILS = "SET_ARTIST_DETAILS";
export const SET_ARTIST_TRACKS = "SET_ARTIST_TRACKS";
export const SET_ARTIST_ALBUMS = "SET_ARTIST_ALBUMS";
export const SET_RELATED_ARTISTS = "SET_RELATED_ARTISTS";

//Your library page
export const SET_FOLLOWED_ARTISTS = "SET_FOLLOWED_ARTISTS";
export const SET_FOLLOWED_TRACKS = "SET_FOLLOWED_TRACKS";

//Follow API
export const UNFOLLOW_ARTIST = "UNFOLLOW_ARTIST";
export const UNFOLLOW_PLAYLIST = "UNFOLLOW_PLAYLIST";