export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";

export const SET_SEARCH_TRACK = "SET_SEARCH_TRACK";
export const SET_SEARCH_ARTIST = "SET_SEARCH_ARTIST";
export const SET_SEARCH_ALBUM = "SET_SEARCH_ALBUM";
export const SET_SEARCH_PLAYLIST = "SET_SEARCH_PLAYLIST";
